#Êý¾Ý¿â
spring
  datasource.password=111111
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.username=mysqld
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.url=jdbc:mysql://192.168.1.200:3306/tickets?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.jpa.show-sql=true
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080
logging.level.com.tickets.mapper:debug
spring.profiles.active=test

spring.jackson.date-format=yyy-MM-dd
spring.jackson.time-zone=GMT+8

