server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.200:3306/tickets?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: mysqld
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  jackson:
    date-format: yyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    root: info
